# Generated by Django 5.0.1 on 2024-01-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classmodel",
            name="schedule",
        ),
        migrations.AlterField(
            model_name="journalmodel",
            name="grade",
            field=models.PositiveIntegerField(
                choices=[(2, 2), (3, 3), (4, 4), (5, 5)], verbose_name="Оценка"
            ),
        ),
        migrations.CreateModel(
            name="ScheduleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(max_length=20, verbose_name="День недели"),
                ),
                ("time_start", models.TimeField(verbose_name="Время начала")),
                ("time_end", models.TimeField(verbose_name="Время окончания")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.subjectmodel",
                        verbose_name="Предмет",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classmodel",
            name="schedule",
            field=models.ManyToManyField(
                to="personal.schedulemodel", verbose_name="Расписание класса"
            ),
        ),
    ]
