# Generated by Django 5.0.1 on 2024-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0003_classmodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classmodel",
            name="classroom_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Номер кабинета"
            ),
        ),
        migrations.AlterField(
            model_name="classmodel",
            name="schedule",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="personal.schedulemodel",
                verbose_name="Расписание класса",
            ),
        ),
    ]
