# Generated by Django 5.0.1 on 2024-01-21 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0004_alter_classmodel_classroom_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classmodel",
            name="class_name",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Название класса"
            ),
        ),
        migrations.AlterField(
            model_name="classmodel",
            name="slug",
            field=models.SlugField(
                default=uuid.uuid4, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="journalmodel",
            name="grade",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterField(
            model_name="journalmodel",
            name="quarter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Первая четверть"),
                    ("2", "Вторая четверть"),
                    ("3", "Третья четверть"),
                    ("4", "Четвёртая четверть"),
                ],
                max_length=1,
                null=True,
                verbose_name="Четверть",
            ),
        ),
    ]
