# Generated by Django 5.0.1 on 2024-01-21 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0005_alter_classmodel_class_name_alter_classmodel_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulemodel",
            name="class_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personal.classmodel",
                verbose_name="Класс",
            ),
        ),
        migrations.RemoveField(
            model_name="classmodel",
            name="schedule",
        ),
        migrations.AddField(
            model_name="classmodel",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personal.schedulemodel",
                verbose_name="Расписание класса",
            ),
        ),
    ]
