# Generated by Django 5.0.1 on 2024-01-21 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0011_classmodel_class_schedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classmodel",
            name="class_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personal.schedulesmodel",
                verbose_name="Расписание",
            ),
        ),
    ]
