services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - mynetwork

  django:
    build: .
    command: bash -c "python /home/ubuntu/FourGimSchool/manage.py migrate && gunicorn --bind 0.0.0.0:8000 app.wsgi:application"
    volumes:
      - .:/home/ubuntu/FourGimSchool
      - static:/home/ubuntu/FourGimSchool/static
      - media:/home/ubuntu/FourGimSchool/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - mynetwork

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static:/home/ubuntu/FourGimSchool/static
      - media:/home/ubuntu/FourGimSchool/media
    depends_on:
      - django
    networks:
      - mynetwork

volumes:
  postgres_data:
  static:
  media:


networks:
  mynetwork:
