# Generated by Django 5.0.1 on 2024-01-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="photo",
            field=models.ImageField(
                upload_to="photos/news/%Y/%m/%d/", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="URL"),
        ),
    ]
