# Generated by Django 5.0.1 on 2024-02-18 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content_ky",
            field=models.TextField(null=True, verbose_name="Текст комментария"),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_ru",
            field=models.TextField(null=True, verbose_name="Текст комментария"),
        ),
        migrations.AddField(
            model_name="comment",
            name="news_ky",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="news.news",
                verbose_name="Новость",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="news_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="news.news",
                verbose_name="Новость",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ky",
            field=models.TextField(null=True, verbose_name="Контент"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ru",
            field=models.TextField(null=True, verbose_name="Контент"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
    ]
