# Generated by Django 5.0.1 on 2024-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="files",
        ),
        migrations.AddField(
            model_name="gallery",
            name="description",
            field=models.TextField(
                default="Your default description", verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                default="", upload_to="gallery/images/", verbose_name="Изображение"
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Публикация"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Время создания"
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="time_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Время обновления"),
        ),
        migrations.DeleteModel(
            name="GalleryFile",
        ),
    ]
