# Generated by Django 5.0.1 on 2024-01-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_remove_gallery_files_gallery_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "ordering": ["-time_create", "is_published"],
                "verbose_name": "Галерея",
                "verbose_name_plural": "Галерей",
            },
        ),
        migrations.AlterField(
            model_name="gallery",
            name="description",
            field=models.CharField(
                default="Your default description",
                max_length=50,
                verbose_name="Описание",
            ),
        ),
    ]
