# Generated by Django 5.0.1 on 2024-02-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_gallery_description_ky_gallery_description_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="description",
            field=models.CharField(
                default="Школа гимназии номер - 4",
                max_length=50,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="description_ky",
            field=models.CharField(
                default="Школа гимназии номер - 4",
                max_length=50,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="description_ru",
            field=models.CharField(
                default="Школа гимназии номер - 4",
                max_length=50,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                upload_to="gallery/images/", verbose_name="Изображение"
            ),
        ),
    ]
