# Generated by Django 5.0.1 on 2024-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_name",
                    models.CharField(max_length=255, verbose_name="Название книги"),
                ),
                (
                    "pdf_book",
                    models.FileField(upload_to="books/", verbose_name="Книга (PDF)"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создание"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Публикация"),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
