# Generated by Django 5.0.1 on 2024-01-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_image",
            field=models.ImageField(
                default=1, upload_to="books_image/", verbose_name="Изображение книги"
            ),
            preserve_default=False,
        ),
    ]
