# Generated by Django 5.0.1 on 2024-02-18 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_ky",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_ky",
            field=models.TextField(null=True, verbose_name="Текст комментария"),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_ru",
            field=models.TextField(null=True, verbose_name="Текст комментария"),
        ),
        migrations.AddField(
            model_name="comment",
            name="post_ky",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="forum.post",
                verbose_name="Пост",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="forum.post",
                verbose_name="Пост",
            ),
        ),
    ]
