# Generated by Django 5.0.1 on 2024-01-27 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
    ]
