# Generated by Django 5.0.1 on 2024-01-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
