# Generated by Django 5.0.1 on 2024-02-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_alter_event_slug_alter_event_time_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="content_ky",
            field=models.TextField(null=True, verbose_name="Контент"),
        ),
        migrations.AddField(
            model_name="event",
            name="content_ru",
            field=models.TextField(null=True, verbose_name="Контент"),
        ),
        migrations.AddField(
            model_name="event",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="event",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
    ]
