# Generated by Django 5.0.1 on 2024-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackmodel",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="feedbackmodel",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="rulesmodel",
            name="number_rule",
            field=models.IntegerField(unique=True, verbose_name="Номер правило"),
        ),
    ]
