# Generated by Django 5.0.1 on 2024-02-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_categorymodel_name_ky_categorymodel_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmodel",
            name="message_ky",
            field=models.TextField(null=True, verbose_name="Сообщение"),
        ),
        migrations.AddField(
            model_name="contactmodel",
            name="message_ru",
            field=models.TextField(null=True, verbose_name="Сообщение"),
        ),
        migrations.AddField(
            model_name="feedbackmodel",
            name="message_ky",
            field=models.TextField(null=True, verbose_name="Введите отзыв"),
        ),
        migrations.AddField(
            model_name="feedbackmodel",
            name="message_ru",
            field=models.TextField(null=True, verbose_name="Введите отзыв"),
        ),
    ]
