# Generated by Django 5.0.1 on 2024-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0002_alter_history_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="files",
            field=models.ManyToManyField(
                related_name="histories",
                to="history.mediafiles",
                verbose_name="видео или файлы",
            ),
        ),
    ]
