# Generated by Django 5.0.1 on 2024-02-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0003_alter_history_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="content_ky",
            field=models.TextField(null=True, verbose_name="Контент"),
        ),
        migrations.AddField(
            model_name="history",
            name="content_ru",
            field=models.TextField(null=True, verbose_name="Контент"),
        ),
        migrations.AddField(
            model_name="history",
            name="description_ky",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="history",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="history",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="history",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
    ]
