# Generated by Django 5.0.1 on 2024-01-21 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personal",
            "0006_schedulemodel_class_name_remove_classmodel_schedule_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulemodel",
            name="class_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="personal.classmodel",
                verbose_name="Класс",
            ),
        ),
    ]
