# Generated by Django 5.0.1 on 2024-01-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0007_alter_schedulemodel_class_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalmodel",
            name="student",
        ),
        migrations.AddField(
            model_name="journalmodel",
            name="student",
            field=models.ManyToManyField(
                to="personal.studentsmodel", verbose_name="Ученик"
            ),
        ),
    ]
