# Generated by Django 5.0.1 on 2024-01-21 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0008_remove_journalmodel_student_journalmodel_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classmodel",
            name="class_journal",
        ),
        migrations.RemoveField(
            model_name="schedulemodel",
            name="class_name",
        ),
        migrations.RemoveField(
            model_name="schedulemodel",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="classmodel",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="studentsmodel",
            name="student_class",
        ),
        migrations.CreateModel(
            name="SchedulesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=3, unique=True, verbose_name="URL"),
                ),
                (
                    "day1example1",
                    models.CharField(max_length=30, verbose_name="День 1 урок 1"),
                ),
                (
                    "day1example2",
                    models.CharField(max_length=30, verbose_name="День 1 урок 2"),
                ),
                (
                    "day1example3",
                    models.CharField(max_length=30, verbose_name="День 1 урок 3"),
                ),
                (
                    "day1example4",
                    models.CharField(max_length=30, verbose_name="День 1 урок 4"),
                ),
                (
                    "day1example5",
                    models.CharField(max_length=30, verbose_name="День 1 урок 5"),
                ),
                (
                    "day1example6",
                    models.CharField(max_length=30, verbose_name="День 1 урок 6"),
                ),
                (
                    "day2example1",
                    models.CharField(max_length=30, verbose_name="День 2 урок 1"),
                ),
                (
                    "day2example2",
                    models.CharField(max_length=30, verbose_name="День 2 урок 2"),
                ),
                (
                    "day2example3",
                    models.CharField(max_length=30, verbose_name="День 2 урок 3"),
                ),
                (
                    "day2example4",
                    models.CharField(max_length=30, verbose_name="День 2 урок 4"),
                ),
                (
                    "day2example5",
                    models.CharField(max_length=30, verbose_name="День 2 урок 5"),
                ),
                (
                    "day2example6",
                    models.CharField(max_length=30, verbose_name="День 2 урок 6"),
                ),
                (
                    "day3example1",
                    models.CharField(max_length=30, verbose_name="День 3 урок 1"),
                ),
                (
                    "day3example2",
                    models.CharField(max_length=30, verbose_name="День 3 урок 2"),
                ),
                (
                    "day3example3",
                    models.CharField(max_length=30, verbose_name="День 3 урок 3"),
                ),
                (
                    "day3example4",
                    models.CharField(max_length=30, verbose_name="День 3 урок 4"),
                ),
                (
                    "day3example5",
                    models.CharField(max_length=30, verbose_name="День 3 урок 5"),
                ),
                (
                    "day3example6",
                    models.CharField(max_length=30, verbose_name="День 3 урок 6"),
                ),
                (
                    "day4example1",
                    models.CharField(max_length=30, verbose_name="День 4 урок 1"),
                ),
                (
                    "day4example2",
                    models.CharField(max_length=30, verbose_name="День 4 урок 2"),
                ),
                (
                    "day4example3",
                    models.CharField(max_length=30, verbose_name="День 4 урок 3"),
                ),
                (
                    "day4example4",
                    models.CharField(max_length=30, verbose_name="День 4 урок 4"),
                ),
                (
                    "day4example5",
                    models.CharField(max_length=30, verbose_name="День 4 урок 5"),
                ),
                (
                    "day4example6",
                    models.CharField(max_length=30, verbose_name="День 4 урок 6"),
                ),
                (
                    "day5example1",
                    models.CharField(max_length=30, verbose_name="День 5 урок 1"),
                ),
                (
                    "day5example2",
                    models.CharField(max_length=30, verbose_name="День 5 урок 2"),
                ),
                (
                    "day5example3",
                    models.CharField(max_length=30, verbose_name="День 5 урок 3"),
                ),
                (
                    "day5example4",
                    models.CharField(max_length=30, verbose_name="День 5 урок 4"),
                ),
                (
                    "day5example5",
                    models.CharField(max_length=30, verbose_name="День 5 урок 5"),
                ),
                (
                    "day5example6",
                    models.CharField(max_length=30, verbose_name="День 5 урок 6"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создание"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновление"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Публикация"),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.classmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписания",
                "verbose_name_plural": "Расписании",
                "ordering": ["-time_create", "id"],
            },
        ),
        migrations.DeleteModel(
            name="JournalModel",
        ),
        migrations.DeleteModel(
            name="ScheduleModel",
        ),
        migrations.DeleteModel(
            name="StudentsModel",
        ),
    ]
