# Generated by Django 5.0.1 on 2024-01-21 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0009_remove_classmodel_class_journal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalmodel",
            name="class_teacher_of",
        ),
    ]
