# Generated by Django 5.0.1 on 2024-01-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0012_alter_classmodel_class_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulesmodel",
            name="slug",
            field=models.SlugField(max_length=10, unique=True, verbose_name="URL"),
        ),
    ]
