# Generated by Django 5.0.1 on 2024-01-23 10:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0013_alter_schedulesmodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulesmodel",
            name="class_name",
            field=models.CharField(max_length=10, verbose_name="Название класса"),
        ),
        migrations.AlterField(
            model_name="schedulesmodel",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=10,
                populate_from="class_name",
                unique=True,
                verbose_name="URL",
            ),
        ),
    ]
