# Generated by Django 5.0.1 on 2024-01-23 10:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0016_alter_schedulesmodel_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedulesmodel",
            options={
                "ordering": ["class_name", "-time_create", "id"],
                "verbose_name": "Расписания",
                "verbose_name_plural": "Расписании",
            },
        ),
        migrations.AlterField(
            model_name="schedulesmodel",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=10,
                populate_from="class_name",
                unique=True,
                verbose_name="URL",
            ),
        ),
    ]
