# Generated by Django 5.0.1 on 2024-01-23 10:15

import autoslug.fields
import uuid
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0017_alter_schedulesmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classmodel",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=uuid.uuid4,
                editable=True,
                populate_from="class_name",
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
