# Generated by Django 5.0.1 on 2024-01-23 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0018_alter_classmodel_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classmodel",
            options={
                "ordering": ["class_name", "-time_create", "id"],
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
            },
        ),
        migrations.AlterModelOptions(
            name="personalmodel",
            options={
                "ordering": ["-work_experience", "-age", "-time_create", "id"],
                "verbose_name": "Персонал",
                "verbose_name_plural": "Персоналы",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectmodel",
            options={"verbose_name": "Предмет", "verbose_name_plural": "Предметы"},
        ),
    ]
