# Generated by Django 5.0.1 on 2024-01-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personal",
            "0019_alter_classmodel_options_alter_personalmodel_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalmodel",
            name="subjects_taught",
            field=models.ManyToManyField(
                to="personal.subjectmodel",
                verbose_name="Преподаваемые предметы или должность",
            ),
        ),
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                (
                    "passport_number",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        verbose_name="Номер паспорта (ID1234567)",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        verbose_name="Персональный номер (ИНН)",
                    ),
                ),
                (
                    "citizenship",
                    models.CharField(max_length=50, verbose_name="Гражданство"),
                ),
                ("address", models.TextField(verbose_name="Адрес проживания")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужской"), ("F", "Женский")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="personal.classmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
                "ordering": ["id", "date_of_birth"],
            },
        ),
    ]
