# Generated by Django 5.0.1 on 2024-01-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0021_gradesstudents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradesstudents",
            name="grade",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                verbose_name="Оценка ученика",
            ),
        ),
        migrations.AlterField(
            model_name="gradesstudents",
            name="quarter",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name="Четверть"
            ),
        ),
    ]
