# Generated by Django 5.0.1 on 2024-01-31 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0022_alter_gradesstudents_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradesstudents",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="StudentGrade",
                to="personal.studentmodel",
                verbose_name="Ученик",
            ),
        ),
        migrations.AlterField(
            model_name="gradesstudents",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="SubjectGrade",
                to="personal.subjectmodel",
                verbose_name="Предмет",
            ),
        ),
    ]
