# Generated by Django 5.0.1 on 2024-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0023_alter_gradesstudents_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalmodel",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Отчество"
            ),
        ),
    ]
