# Generated by Django 5.0.1 on 2024-02-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0024_personalmodel_patronymic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authorities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorities_person",
                        to="personal.personalmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Начальство",
                "verbose_name_plural": "Начальство",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Parliament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        upload_to="parliaments_person_pictures/",
                        verbose_name="Фото профиля",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parliaments_person",
                        to="personal.studentmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Парламент ",
                "verbose_name_plural": "Парламенты",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RetiredTeachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="RetiredTeachers_person",
                        to="personal.personalmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учителя в отставке ",
                "verbose_name_plural": "Учителя в отставке",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers_person",
                        to="personal.personalmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учителя ",
                "verbose_name_plural": "Учителя",
                "ordering": ["id"],
            },
        ),
    ]
