# Generated by Django 5.0.1 on 2024-02-20 18:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0026_authorities_is_published_authorities_time_create_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classmodel",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                populate_from="class_name",
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
