# Generated by Django 5.0.1 on 2024-01-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Документ", "verbose_name_plural": "Документы"},
        ),
        migrations.AlterField(
            model_name="document",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Публикация"),
        ),
        migrations.AlterField(
            model_name="document",
            name="pdf_file",
            field=models.FileField(
                upload_to="documents/", verbose_name="Документ (PDF)"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создание"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
    ]
