# Generated by Django 5.0.1 on 2024-02-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("personal", "0023_alter_gradesstudents_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitiveAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                ("description", models.TextField(verbose_name="Описание достижение")),
                (
                    "image_student",
                    models.ImageField(
                        upload_to="image_best_student/", verbose_name="Фото ученика"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
            ],
            options={
                "verbose_name": "Достижение ученика",
                "verbose_name_plural": "Достижении учеников",
            },
        ),
        migrations.CreateModel(
            name="AchievementPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание достижение")),
                (
                    "image_personal",
                    models.ImageField(
                        upload_to="image_best_personal/", verbose_name="Фото ученика"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.personalmodel",
                        verbose_name="Учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Достижение ученика",
                "verbose_name_plural": "Достижении учеников",
            },
        ),
        migrations.CreateModel(
            name="AchievementStudents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                ("description", models.TextField(verbose_name="Описание достижение")),
                (
                    "image_student",
                    models.ImageField(
                        upload_to="image_students/", verbose_name="Фото ученика"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "class_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_students",
                        to="personal.classmodel",
                        verbose_name="Класс ученика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Достижение ученика",
                "verbose_name_plural": "Достижении учеников",
            },
        ),
        migrations.CreateModel(
            name="BestStudents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "image_student",
                    models.ImageField(
                        upload_to="image_best_student/", verbose_name="Фото ученика"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "class_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="best_students",
                        to="personal.classmodel",
                        verbose_name="Класс ученика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лучший ученик",
                "verbose_name_plural": "Лучшие ученики",
            },
        ),
    ]
