# Generated by Django 5.0.1 on 2024-02-01 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("achievement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievementstudents",
            name="class_student",
        ),
    ]
