# Generated by Django 5.0.1 on 2024-02-02 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("achievement", "0002_remove_achievementstudents_class_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievementpersonal",
            options={
                "verbose_name": "Достижение учителя",
                "verbose_name_plural": "Достижении учителей",
            },
        ),
        migrations.AlterModelOptions(
            name="competitiveachievement",
            options={
                "verbose_name": "Соревновательные Достижение",
                "verbose_name_plural": "Соревновательные Достижении",
            },
        ),
    ]
