# Generated by Django 5.0.1 on 2024-02-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievement", "0003_alter_achievementpersonal_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementpersonal",
            name="description_ky",
            field=models.TextField(null=True, verbose_name="Описание достижение"),
        ),
        migrations.AddField(
            model_name="achievementpersonal",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание достижение"),
        ),
        migrations.AddField(
            model_name="achievementstudents",
            name="description_ky",
            field=models.TextField(null=True, verbose_name="Описание достижение"),
        ),
        migrations.AddField(
            model_name="achievementstudents",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание достижение"),
        ),
        migrations.AddField(
            model_name="competitiveachievement",
            name="description_ky",
            field=models.TextField(null=True, verbose_name="Описание достижение"),
        ),
        migrations.AddField(
            model_name="competitiveachievement",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание достижение"),
        ),
    ]
